---
layout: cv
title: Seth Tucker's CV
---
# Seth Tucker
Programmer, Business Analyst.

<div id="webaddress">
<a href="thesethtucker@gmail.com">thesethtucker@gmail.com</a>
| <a href="https://www.linkedin.com/in/seth-tucker19/">My LinkedIn</a>
</div>


## Currently

Student at Brigham Young University - Idaho

### Studying

Business Analytics, with a Minor in Data Science


### Research interests

Analyzing data with queries using MySQL, Python, and advanced Microsoft Excel features


## Education

`2019`
__Bowman Prep Academy (High School Graduation)__

`Fall 2020 - Present`
__Brigham Young University - Idaho__


## Achievements

`October 2016` Eagle Scout

`Spring 2017` Recognized as hardest worker on Outdoor Track Team, Northern Guilford High School

`Winter 2017-18` Captain of Indoor Track Team, Northern Guilford High School



## Past Work Experience

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Sportswriter | Post Register | March 2024 - December 2024

Write articles about high school sports by researching teams, players, and coaches before events, attending and viewing the sporting event, and interviewing players and coaches 

Analyze sports statistics to find interesting insights to share in articles 

### LEAD ASSOCIATE | DESERET INDUSTRIES | JANUARY 2022 – APRIL 2023

Worked on the receiving end of donations, greeting and helping donors unload their vehicles and placing their donations on carts, baled unsold and unsellable clothing, operated forklift to move bales and pallets of items around, as well as priced and cleaned large items for the sales floor.

### SPORTSWRITER INTERNSHIP | CAROLINA COBRAS | APRIL 2018 – APRIL 2019 

Responsible for the majority of written content on the Cobras’ website including writing game previews, post-game recaps, articles for the game-day program, and player signings.  

Interviewed coaches and players to bolster these articles and developed relationships with these people to get inside scoops and create compelling content. 

Appeared on the halftime show of broadcasts to provide player insights to thousands of viewers.



<!-- ### Footer

Last updated: April 2025 -->